name: nlp_tweets
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - pandas>=1.5.0
  - matplotlib>=3.5.0
  - datasets>=2.0.0
  - tqdm
  - scikit-learn>=1.3.0
  - seaborn
  - pyarrow>=21.0.0
  - nltk
  - spacy
  - emoji
  - anthropic
  #create your environment run: conda env create -f environment.yml
  #or update your environment run: conda env update --f environment.yml --prune
  #activate your environment run : conda activate nlp_tweets